Update Maven deploy script

diff --git a/.github/workflows/archiving.yml b/.github/workflows/archiving.yml
--- a/.github/workflows/archiving.yml
+++ b/.github/workflows/archiving.yml
@@ -19,9 +19,10 @@ jobs:
           run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
         - name: archive
           run: |
-           (echo "===== Attemp 1 =====" && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -PArchiving exec:java)
-           || (echo "===== Attemp 2 =====" && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -PArchiving exec:java)
-           || (echo "===== Attemp 3 =====" && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -PArchiving exec:java)  
+            (echo "===== Maven Deploy Attempt: 1 ====" && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -PArchiving exec:java) || \
+            (echo "===== Maven Deploy Attempt: 2 ====" && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -PArchiving exec:java) || \
+            (echo "===== Maven Deploy Attempt: 3 ====" && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -PArchiving exec:java) || \
+            (echo "==== Maven Deploy Step Failed ====" && exit 1)
           env:
             MAIL : ${{ secrets.TEST_MAIL }}
             PASSWORD : ${{ secrets.TEST_PASSWORD }}
